spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: parking_2019
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: parking

server:
  port: 8081
